### ISSUE TITLE
Error in exomePeak and MeTDiff modules

### ISSUE THREAD

**Issue by sunqiangzai** [shunliubio/easym6A#1]
Dear,

I have ran into a problems in the m6A analysis using the test data.

![image](https://user-images.githubusercontent.com/22913048/123244357-6ecf2c80-d516-11eb-8dc0-60efc55c5506.png)
![image](https://user-images.githubusercontent.com/22913048/123244482-8dcdbe80-d516-11eb-92e5-6c4e406f2994.png)

**Comment by shunliubio** [comment]
Hi,

I can not reproduce the issue. Did bash_log report any errors? Or I guess your bam and gtf files have something inconsistent with each other.
