### ISSUE TITLE
error in using easym6A

### ISSUE THREAD

**Issue by yangyingwu** [shunliubio/easym6A#2]
we used the perl script (perl easym6A_local.pl -s sampleList.txt -c configuration.txt -n 1,2 -e EMG -t 4 -r), but returned the following errors. I don't know the reason. Can you help us solve this problem?  （we prepared the sampleList.txt and configuration.txt according to the easym6A guide.  we used the paired-end data)

**Use of uninitialized value $fileName in hash element at easym6A_local.pl line 640.
Use of uninitialized value within %fqFile in split at easym6A_local.pl line 640.
number of fq file is either 1 for single-end or 2 for paired-end!**

**Comment by shunliubio** [comment]
easym6A could not find file names and the setting in the field `Fastq File` was not correct. Possibly there was something wrong with the format of sampleList.txt. The file includes 19 fields. Note that leave a character `-` if no information is available in the corresponding field.

**Comment by yangyingwu** [comment]
Hello Shun Liu
Thank you for your reply.
My sampleList.txt was prepared as follows:
Species	Cell Line	Dataset	Sample	Group	File Name	Fastq File Dir	fastq File	bam File Path	5' Adapter	3' Adapter	5' Barcode	3' Barcode	Q33	Strandness	Fragment Length	Read Length	Seq Layout	ID
tomato	fruit	-	EMG	EMG_Input	input_EMG	/home/yyw/software/easym6A/data	input_EMG_r1.fastq.gz,input_EMG_r2.fastq.gz	-	-	AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT	-	-	Y	U	150	50	PAIRED	1
tomato	fruit	-	EMG	EMG_IP	ip_EMG	/home/yyw/software/easym6A/data	ip_EMG_r1.fastq.gz,ip_EMG_r2.fastq.gz	-	-	AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC,GATCGTCGGACTGTAGAACTCTGAAC	-	-	Y	U	150	50	PAIRED	2

The line 640 in easym6A_local.pl is: my @fqFile=split /,/,$fqFile{$fileName};

Please help me analyze the error.

**Comment by shunliubio** [comment]
It seems like no errors in your file except that the file should be tab-delimited. Can you confirm that each field is separated by a tab?

**Comment by yangyingwu** [comment]
Yes. I can be sure that each field is separated by a tab.

**Comment by shunliubio** [comment]
Possibly it is a line-ending problem. I can reproduce this error if Windows-style line-endings are used in sampleList.txt. easym6A only supports Unix-style line-endings. You can use `dos2unix` to convert your files to Unix line breaks.
